
# model 
embedding_dim: 128
temperature: 0.07

# optimizer
optimizer_name: 'sgd'
learning_rate: 0.03
weight_decay: 1.0e-5
momentum: 0.9

# training
epochs: 200
batch_size: 256

# save/load -- relative to path of script file
load_filepath: null    
save_filepath: '../expts/sample_expt/simclr_pretrained_weights.h5'