

# dataset
data:
  dataset_name: speech_commands

# model 
model: 
  embedding_dim: 128
  temperature: 0.50
  viewmaker_loss_weight: 1.0 
  distortion_budget: 0.05

# unsupervised pretraining:
pretrain:
  optimizer_name: 'sgd'
  learning_rate: 0.03
  weight_decay: 1.0e-5
  momentum: 0.9
  epochs: 1
  batch_size: 16

# supervised finetuning
transfer:
  optimizer_name: 'sgd'
  learning_rate: 0.01
  weight_decay: 0.0
  momentum: 0.9
  epochs: 1
  batch_size: 16

# evaluation
evaluation:
  batch_size: 256

# save/load
experiment_directory: C:\Users\Paul\viewmaker_reproduction\experiments\test_expt