

# dataset
data:
  dataset_name: mnist

# model 
model: 
  embedding_dim: 128
  temperature: 0.50
  viewmaker_loss_weight: 1.0 
  distortion_budget: 0.05

# unsupervised pretraining:
pretrain:
  optimizer_name: 'sgd'
  learning_rate: 0.03
  weight_decay: 1.0e-4
  momentum: 0.9
  epochs: 1000
  batch_size: 256

# supervised finetuning
transfer:
  optimizer_name: 'sgd'
  learning_rate: 0.01
  weight_decay: 0.0
  momentum: 0.9
  epochs: 20
  batch_size: 256

# evaluation
evaluation:
  batch_size: 256

# save/load
experiment_directory: /home/ayesha/Desktop/CISC867/viewmaker_reproduction/experiments/experiment8