
# model 
embedding_dim: 128
temperature: 0.07
viewmaker_loss_weight: 1.0 #only needed if using viewmaker
distortion_budget: 0.05

# optimizer
optimizer_name: 'sgd'
learning_rate: 0.01
weight_decay: 0.0
momentum: 0.9

# training
train: true                                 # false if just running the script for evaluation
epochs: 100
batch_size: 256

# evaluation
eval_batch_size: 256

# save/load
log_directory: ../expts/sample_expt/log
load:
  pretrained_viewmaker_weights: /home/ayesha/Desktop/CISC867/viewmaker_reproduction/experiments/experiment3/viewmaker_pretrained_weights.h5
  pretrained_classifier_weights: null        # if using for evaluation not training
save:
  classifier_weights: /home/ayesha/Desktop/CISC867/viewmaker_reproduction/experiments/experiment3/viewmaker_transfer_weights.h5

