# model 
embedding_dim: 128
temperature: 0.50
viewmaker_loss_weight: 1.0 
disortion_budget: 0.05

# optimizer
optimizer_name: 'sgd'
learning_rate: 0.03
weight_decay: 1.0e-5
momentum: 0.9

# training
epochs: 200
batch_size: 256

# save/load 
log_directory: ../expts/sample_expt/log   # for tensorboard
load_filepath: null    
save_filepath: '/home/ayesha/Desktop/CISC867/viewmaker_reproduction/experiments/experiment3'